config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :carousels do
      resources :slides do
        collection do
          patch :sort
        end
      end
    end
  end
end

app/models/spree/fairground.rb
module Spree::Fairground
  def self.table_name_prefix
    'spree_fairground_'
  end
  def self.use_relative_model_naming?
    true
  end
end

app/models/spree/fairground/carousel.rb
class Spree::Fairground::Carousel < ActiveRecord::Base
  has_many :slides, -> { order(position: :asc) }, class_name: 'Spree::Fairground::Slide'
  validates_presence_of :name
  validates_uniqueness_of :name
  accepts_nested_attributes_for :slides, allow_destroy: true
end

app/models/spree/fairground/slide.rb
class Spree::Fairground::Slide < ActiveRecord::Base
  has_attached_file :attachment,
                    styles: { mobile: '479x479>', tablet: '786x768>', desktop_small: '980x980>', desktop: '1200x1200>' },
                    default_style: :desktop,
                    url: '/spree/slides/:id/:style/:basename.:extension',
                    path: ':rails_root/public/spree/slides/:id/:style/:basename.:extension',
                    convert_options: { all: '-strip -auto-orient -colorspace sRGB' }

  with_options if: :image_slide? do |slide|
    slide.validate :no_attachment_errors
    slide.validates_attachment :attachment,
      presence: true,
      content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }
    slide.validates :link, presence: true
  end

  validates :body, presence: true, if: :html_slide?

  belongs_to :carousel, required: true

  acts_as_list scope: :carousel

  # save the w,h of the original image (from which others can be calculated)
  # we need to look at the write-queue for images which have not been saved yet
  after_post_process :find_dimensions

  def image_slide?
    slide_type.downcase == "image"
  end

  def html_slide?
    slide_type.downcase == "html"
  end

  def find_dimensions
    temporary = attachment.queued_for_write[:original]
    filename = temporary.path unless temporary.nil?
    filename = attachment.path if filename.blank?
    geometry = Paperclip::Geometry.from_file(filename)
    self.attachment_width  = geometry.width
    self.attachment_height = geometry.height
  end

  # if there are errors from the plugin, then add a more meaningful message
  def no_attachment_errors
    unless attachment.errors.empty?
      # uncomment this to get rid of the less-than-useful interim messages
      # errors.clear
      errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
      false
    end
  end
end

app/models/spree/slide.rb
class Spree::Slide < ActiveRecord::Base
  has_attached_file :attachment,
                    styles: { mobile: '479x479>', tablet: '786x768>', desktop_small: '980x980>', desktop: '1200x1200>' },
                    default_style: :desktop,
                    url: '/spree/slides/:id/:style/:basename.:extension',
                    path: ':rails_root/public/spree/slides/:id/:style/:basename.:extension',
                    convert_options: { all: '-strip -auto-orient -colorspace sRGB' }

  with_options if: :image_slide? do |slide|
    slide.validate :no_attachment_errors
    slide.validates_attachment :attachment,
      presence: true,
      content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }
    slide.validates :link, presence: true
  end

  validates :body, presence: true, if: :html_slide?

  belongs_to :carousel, required: true

  acts_as_list scope: :carousel

  # save the w,h of the original image (from which others can be calculated)
  # we need to look at the write-queue for images which have not been saved yet
  after_post_process :find_dimensions

  def image_slide?
    slide_type.downcase == "image"
  end

  def html_slide?
    slide_type.downcase == "html"
  end

  def find_dimensions
    temporary = attachment.queued_for_write[:original]
    filename = temporary.path unless temporary.nil?
    filename = attachment.path if filename.blank?
    geometry = Paperclip::Geometry.from_file(filename)
    self.attachment_width  = geometry.width
    self.attachment_height = geometry.height
  end

  # if there are errors from the plugin, then add a more meaningful message
  def no_attachment_errors
    unless attachment.errors.empty?
      # uncomment this to get rid of the less-than-useful interim messages
      # errors.clear
      errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
      false
    end
  end
end

app/controllers/spree/admin/carousels_controller.rb
class Spree::Admin::CarouselsController < Spree::Admin::BaseController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @carousels = Spree::Fairground::Carousel.all
  end

  def show
    @slides = @carousel.slides
  end

  def new
    @carousel = Spree::Fairground::Carousel.new
  end

  def edit
  end

  def create
    @carousel = Spree::Fairground::Carousel.new(carousel_params)

    if @carousel.save
      redirect_to admin_carousel_url(@carousel), notice: 'Carousel was successfully created.'
    else
      render :new
    end
  end

  def update
    if @carousel.update(carousel_params)
      redirect_to admin_carousel_url(@carousel), notice: 'Carousel was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @carousel.destroy
    redirect_to admin_carousels_url, notice: 'Carousel was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @carousel = Spree::Fairground::Carousel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def carousel_params
      params.require(:carousel).permit(:name, slides_attributes: [:attachment, :feature_id, :feature_value, :alt])
    end
end

app/controllers/spree/admin/slides_controller.rb
class Spree::Admin::SlidesController < Spree::Admin::BaseController
  before_action :set_parent_resource
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @slides= @carousel.slides.all
  end

  def show
  end

  def new
    @slide = @carousel.slides.new
  end

  def edit
  end

  def create
    @slide = @carousel.slides.new(spree_slide_params)

    if @slide.save
      redirect_to admin_carousel_path(@carousel), notice: 'Slide was successfully created.'
    else
      render :new
    end
  end

  def update
    if @slide.update(spree_slide_params)
      redirect_to admin_carousel_slide_path(@carousel, @slide), notice: 'Slide was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @slide.destroy
    redirect_to admin_carousel_path(@carousel), notice: 'Slide was successfully destroyed.'
  end

  def sort
    updates = params[:sorting].each_with_index do |id, index|
      position = index + 1
      @carousel.slides.find(id).update_column(:position, position)
    end
    respond_to do |format|
      format.json { render json: { success: true }, status: :ok }
    end
  end

  private

    def set_parent_resource
      @carousel = Spree::Fairground::Carousel.find(params[:carousel_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @slide = @carousel.slides.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def spree_slide_params
      params.require(:slide).permit(:attachment, :attachment_file_name, :alt, :link, :body, :slide_type, :sorting)
    end
end

app/helpers/spree/admin/carousels_helper.rb
module Spree::Admin::CarouselsHelper
end

app/helpers/spree/admin/slides_helper.rb
module Spree::Admin::SlidesHelper
end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.module_eval do
  def carousel(view)
    # use view to look up if there's a carousel available
    collection = Spree::Fairground::Carousel.first.slides
    render partial: "spree/carousels/slides", locals: { collection: collection }
  end
end

app/views/spree/admin/carousels/_carousel_settings.html.erb
<form class="form-horizontal">
  <div class="form-group-sm">
    <label for="inputEmail3" class="col-sm-3 control-label">Email</label>
    <div class="col-sm-9">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group-sm">
    <label for="inputPassword3" class="col-sm-3 control-label">Password</label>
    <div class="col-sm-9">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  <div class="form-group-sm">
    <div class="col-sm-offset-3 col-sm-9">
      <div class="checkbox">
        <label>
          <input type="checkbox" checked="checked"> Adaptive Height
        </label>
      </div>
    </div>
  </div>
  <div class="form-group-sm">
    <div class="col-sm-offset-3 col-sm-9">
      <div class="checkbox">
        <label>
          <input type="checkbox" checked="checked"> Arrows
        </label>
      </div>
    </div>
  </div>
  <div class="form-group-sm">
    <div class="col-sm-offset-3 col-sm-9">
      <div class="checkbox">
        <label>
          <input type="checkbox" checked="checked"> Accessiblity
        </label>
      </div>
    </div>
  </div>
  <div class="form-group-sm">
    <div class="col-sm-offset-3 col-sm-9">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>

                accessibility: true,
                adaptiveHeight: false,
                arrows: true,
                asNavFor: null,
                prevArrow: '<button type="button" data-role="none" class="slick-prev" aria-label="previous">Previous</button>',
                nextArrow: '<button type="button" data-role="none" class="slick-next" aria-label="next">Next</button>',
                autoplay: false,
                autoplaySpeed: 3000,
                centerMode: false,
                centerPadding: '50px',
                cssEase: 'ease',
                customPaging: function(slider, i) {
                    return '<button type="button" data-role="none">' + (i + 1) + '</button>';
                },
                dots: false,
                dotsClass: 'slick-dots',
                draggable: true,
                easing: 'linear',
                edgeFriction: 0.35,
                fade: false,
                focusOnSelect: false,
                infinite: true,
                initialSlide: 0,
                lazyLoad: 'ondemand',
                mobileFirst: false,
                pauseOnHover: true,
                pauseOnDotsHover: false,
                respondTo: 'window',
                responsive: null,
                rows: 1,
                rtl: false,
                slide: '',
                slidesPerRow: 1,
                slidesToShow: 1,
                slidesToScroll: 1,
                speed: 500,
                swipe: true,
                swipeToSlide: false,
                touchMove: true,
                touchThreshold: 5,
                useCSS: true,
                variableWidth: false,
                vertical: false,
                verticalSwiping: false,
                waitForAnimate: true
            };

app/views/spree/admin/carousels/_form.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @carousel } %>

<%= f.field_container :name, class: ['form-group'] do %>
  <%= f.label :name, Spree.t(:give_name, scope: :slides) %> <span class="required">*</span>
  <%= f.text_field :name, class: 'form-control name' %>
  <%= f.error_message_on :name %>
<% end %>

app/views/spree/admin/carousels/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t :edit, scope: :slides %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'translate', nil, admin_translations_path('carousel', @carousel.id), title: Spree.t(:'i18n.translations'), class: 'btn btn-sm btn-primary' %>
<% end if can?(:translate, Spree::Fairground::Carousel) %>

<%= form_for [:admin, @carousel], :html => { :multipart => true } do |f| %>
  <%= render partial: 'form', :locals => { :f => f } %>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.edit'), 'ok', 'submit', {class: 'btn-success'} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_carousels_url, :icon => 'remove' %>
  </div>
<% end %>

app/views/spree/admin/carousels/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t :long_name, scope: :slides %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:create, scope: :slides), 
        new_admin_carousel_url, 
        { :class => "btn-success", :icon => 'add', :id => 'admin_new_carousel' } %>
<% end if can?(:create, Spree::Fairground::Carousel) %>

<% if @carousels.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:name, scope: :slides) %></th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @carousels.each do |carousel| %>
      <tr id="<%= spree_dom_id carousel %>" data-hook="admin_carousels_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= link_to carousel.name, admin_carousel_path(carousel) %></td>
        <td class="actions actions-3 text-right" data-hook="admin_carousel_index_row_actions">
          
          <%= link_to_with_icon('delete', nil, admin_carousel_path(carousel),
                title: Spree.t(:delete),
                data: { confirm: Spree.t(:are_you_sure), action: 'remove' }, 
                class: "btn btn-danger btn-sm delete-resource icon-link with-tip action-delete") if can?(:destroy, carousel) %>

          <%= link_to_with_icon('edit', nil, admin_carousel_path(carousel),
                title: Spree.t(:edit),
                data: { action: 'edit' }, 
                class: "btn btn-primary btn-sm icon-link with-tip action-edit") if can?(:edit, carousel)  %>

        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/carousels/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t :new, scope: :slides %>
<% end %>

<%= form_for [:admin, @carousel], :html => { :multipart => true } do |f| %>
  <%= render partial: 'form', :locals => { :f => f } %>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.create'), 'ok', 'submit', {class: 'btn-success'} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_carousels_url, :icon => 'remove' %>
  </div>
<% end %>

app/views/spree/admin/carousels/show.html.erb
<% content_for :page_title do %>
  <%= link_to(Spree.t(:name, scope: :slides), admin_carousels_url) %> / <%= @carousel.name %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_slide, scope: :contents), 
        new_admin_carousel_slide_url(@carousel), 
        { :class => "btn-success", :icon => 'add', :id => 'admin_new_content' } %>
  <%# link_to_with_icon 'translate', nil, admin_translations_path('carousel', @carousel.id), title: Spree.t(:'i18n.translations'), class: 'btn btn-sm btn-primary' if can?(:translate, Spree::Fairground::Carousel) %>
<% end if can?(:create, Spree::Fairground::Carousel) %>

<% if @slides.any? %>
  <div class="row">
    <div class="col-sm-12">
      <p>
        <small>Drag thumbs to sort, click them to edit</small>
        <button class="hidden btn btn-success btn-xs" id="update-sorting">Save new order</button>
      </p>
    </div>
    <div class="col-sm-12">
      <ul id="carousel-thumbs" class="ui-sortable list-inline carousel-thumbs">
        <%- @slides.each do |slide| -%>
          <%= render partial: "spree/admin/slides/thumb_#{slide.slide_type}", locals: { slide: slide } %>
        <%- end -%>
      </ul>
    </div>
    <div class="col-md-8 text-center carousel-viewport">
      <div id="<%= spree_dom_id @carousel %>" class="carousel" data-carousel data-sorting-url="<%= sort_admin_carousel_slides_url(@carousel) %>">
      <%- @slides.each do |slide| -%>
        <%= render partial: "spree/slides/slide_#{slide.slide_type}", locals: { slide: slide } %>
      <%- end -%>
      </div>
    </div>
    <div class="col-md-4">
      <p><i class="fa fa-bomb"></i> <small>some settings like, speed, transitions etc to come here soon...</small></p>
      <%#= render partial: "carousel_settings" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    var Carousel = {
      element: function(){
        return $("[data-carousel]");
      },
      items: function(){
        return this.element().find('.carousel-slide-item');
      },
      state: {
        unfinished: false
      },
      start: function() {
        this.element().slick({
          dots: true,
          arrows: true,
          infinite: true,
          speed: 500,
          fade: true,
          cssEase: 'linear',
          autoplay: true,
          autoplaySpeed: 3000,
        });
      }, 
      stop: function(){
        this.element().slick('unslick');
        return this.element();
      }
    };
    Carousel.start();
    window.Spree.Carousel = Carousel;
  });
</script>

app/views/spree/admin/slides/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <%= f.label :slide_type, Spree.t(:slide_type, scope: :slides) %>
      <%= f.select :slide_type, 
            options_for_select([[Spree.t(:image), 'image'],[Spree.t(:html),'html']]), 
            {}, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row image-attribute">
  <div class="col-md-6">
    <div data-hook="file" class="form-group">
      <%= f.label :attachment, Spree.t(:filename) %>
      <%= f.file_field :attachment %>
    </div>
  </div>
  <div data-hook="alt_text" class="col-md-6">
    <%= render(partial: "image_preview", locals: { slide: f.object }) if f.object.attachment? %>
    <div class="form-group">
      <%= f.label :alt, Spree.t(:alt_text) %>
      <%= f.text_field :alt, class: 'form-control' %>
    </div>
    <div data-hook="link" class="form-group">
      <%= f.label :link, Spree.t(:link) %>
      <%= f.text_field :link, class: 'form-control' %>
    </div>
  </div>
</div>
<div class="row html-attribute">
  <div class="col-sm-12">
    <div class="form-group">
      <%= f.label :body, Spree.t(:body) %>
      <%= f.text_area :body, class: 'summernote' %>
    </div>
  </div>
</div>

<script>
  var attrs = {
    image: {
      hide: ".html-attribute",
      show: ".image-attribute"
    }, 
    html: {
      hide: ".image-attribute",
      show: ".html-attribute"
    }
  };
  var displayFields = function(context) {
    $(attrs[context].hide).hide();
    $(attrs[context].show).show();
  };
  displayFields($('#slide_slide_type').val());
  $('#slide_slide_type').on('change', function(e){
    $('#slide_slide_type').val();
    displayFields(this.value);
  });
</script>

app/views/spree/admin/slides/_image_preview.html.erb
<div class="row">
  <div class="col-sm-12 text-center">
    <%= image_tag(@slide.attachment.url(:tablet), class: "img-responsive") %>
  </div>
</div>

app/views/spree/admin/slides/_thumb_html.erb
<li data-slide-id="<%= slide.id %>">
  this contains html...
</li>

app/views/spree/admin/slides/_thumb_image.html.erb
<li data-slide-id="<%= slide.id %>">
<%= link_to edit_admin_carousel_slide_path(slide.carousel_id, slide) do  -%>
  <%= image_tag(slide.attachment.url(:mobile), class: "carousel-thumb") %>
<%- end -%>
</li>

app/views/spree/admin/slides/edit.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @slide } %>

<% content_for :page_title do %>
  <%= link_to(Spree.t(:name, scope: :slides), admin_carousels_url) %> / <%= link_to @carousel.name, admin_carousel_url(@carousel) %> / Slide <%= @slide.position %>
<% end %>

<%= form_for [:admin, @carousel, @slide], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_carousel_slides_url(@carousel), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Spree Slides</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spree_slides.each do |spree_slide| %>
      <tr>
        <td><%= link_to 'Show', spree_slide %></td>
        <td><%= link_to 'Edit', edit_spree_slide_path(spree_slide) %></td>
        <td><%= link_to 'Destroy', spree_slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/slides/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @slide } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_image) %>
<% end %>

<%= form_for [:admin, @carousel, @slide], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_carousel_slides_url(@carousel), icon: 'delete', id: 'cancel_link' %>
    </div>
    
  </fieldset>
<% end %>

app/views/spree/admin/slides/show.html.erb
<% content_for :page_title do %>
  <%= link_to(Spree.t(:name, scope: :slides), admin_carousels_url) %> / <%= link_to @carousel.name, admin_carousel_url(@carousel) %> / Slide X
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_slide, scope: :contents), 
        new_admin_carousel_slide_url(@carousel), 
        { :class => "btn-success", :icon => 'add', :id => 'admin_new_content' } %>
  <%# link_to_with_icon 'translate', nil, admin_translations_path('carousel', @carousel.id), title: Spree.t(:'i18n.translations'), class: 'btn btn-sm btn-primary' if can?(:translate, Spree::Fairground::Carousel) %>
<% end if can?(:create, Spree::Fairground::Carousel) %>

app/views/spree/slides/_slide_html.erb
<div id="<%= spree_dom_id(slide) %>" class="carousel-slide-item text-left">
  <%= raw slide.body %>
</div>

app/views/spree/slides/_slide_image.html.erb
<div id="<%= spree_dom_id(slide) %>" class="carousel-slide-item">
  <%= link_to image_tag(slide.attachment.url, alt: slide.alt, class: "img-responsive"), slide.link %>
</div>